{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH seg AS (
    SELECT 
    COALESCE(l.NAME, u.CALLED_CONTRACT) AS PROJECT,
    CHAIN,
    COUNT(DISTINCT u.SENDER) AS NUM_UNIQUE_SENDERS,
    COUNT(u.OP_HASH) AS NUM_OPS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS u
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.ERC4337_LABELS_APPS l ON u.CALLED_CONTRACT = l.ADDRESS
    GROUP BY 1,2
    ORDER BY 3 DESC
    LIMIT 10
)

, agg AS (
    SELECT 
    COALESCE(l.NAME, u.CALLED_CONTRACT) AS PROJECT,
    'all' AS CHAIN,
    COUNT(DISTINCT u.SENDER) AS NUM_UNIQUE_SENDERS,
    COUNT(u.OP_HASH) AS NUM_OPS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS u
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.ERC4337_LABELS_APPS l ON u.CALLED_CONTRACT = l.ADDRESS
    GROUP BY 1,2
    ORDER BY 3 DESC
    LIMIT 10
)

SELECT * FROM agg
union all
SELECT * FROM seg