{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH userops AS (
    SELECT 
    CHAIN,
    COUNT(*) as NUM_USEROPS, 
    COUNT(DISTINCT SENDER) AS NUM_ACCOUNTS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS
    GROUP BY 1

    UNION ALL
    SELECT 
    'all' AS CHAIN,
    COUNT(*) as NUM_USEROPS, 
    COUNT(DISTINCT SENDER) AS NUM_ACCOUNTS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS
    GROUP BY 1    
)

, txns AS (
    SELECT 
    CHAIN,
    COUNT(*) as NUM_TXNS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_ENTRYPOINT_TRANSACTIONS
    GROUP BY 1

    UNION ALL    
    SELECT 
    'all' AS CHAIN,
    COUNT(*) as NUM_TXNS
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_ENTRYPOINT_TRANSACTIONS
    GROUP BY 1
)

, paymaster_spend AS (
    SELECT 
    CHAIN,
    ROUND(SUM(ACTUALGASCOST_USD)) AS GAS_SPENT
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS
    WHERE PAYMASTER != '0x0000000000000000000000000000000000000000'
    AND ACTUALGASCOST_USD != 'NaN'
    AND ACTUALGASCOST_USD < 1000000000
    GROUP BY 1

    UNION ALL
    SELECT 
    'all' AS CHAIN,
    ROUND(SUM(ACTUALGASCOST_USD)) AS GAS_SPENT
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS
    WHERE PAYMASTER != '0x0000000000000000000000000000000000000000'
    AND ACTUALGASCOST_USD != 'NaN'
    AND ACTUALGASCOST_USD < 1000000000
    GROUP BY 1
)

SELECT 
    u.CHAIN,
    u.NUM_USEROPS,
    u.NUM_ACCOUNTS,
    t.NUM_TXNS,
    p.GAS_SPENT
FROM userops u
INNER JOIN txns t ON u.CHAIN = t.CHAIN
INNER JOIN paymaster_spend p ON u.CHAIN = p.CHAIN