{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH day_metrics AS (
SELECT 
TO_VARCHAR(DATE, 'YYYY-MM-DD') as DATE,
'day' AS TIMEFRAME,
chain,
SUM(GAS_SPENT) AS GAS_SPENT
FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_DAY_PAYMASTER_SPEND_CHAIN
WHERE DATE > DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '24 months'
GROUP BY 1,2,3
)

, week_metrics AS (
SELECT 
TO_VARCHAR(date_trunc('week', DATE), 'YYYY-MM-DD') as DATE,
'week' AS TIMEFRAME,
chain,
SUM(GAS_SPENT) AS GAS_SPENT
FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_DAY_PAYMASTER_SPEND_CHAIN
WHERE DATE > DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '24 months'
GROUP BY 1,2,3
)

, month_metrics AS (
SELECT 
TO_VARCHAR(date_trunc('month', DATE), 'YYYY-MM-DD') as DATE,
'month' AS TIMEFRAME,
chain,
SUM(GAS_SPENT) AS GAS_SPENT
FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_DAY_PAYMASTER_SPEND_CHAIN
WHERE DATE > DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '24 months'
GROUP BY 1,2,3
)

SELECT
DATE,
TIMEFRAME,
CHAIN,
GAS_SPENT
FROM day_metrics

UNION ALL
SELECT
DATE,
TIMEFRAME,
CHAIN,
GAS_SPENT
FROM week_metrics

UNION ALL
SELECT
DATE,
TIMEFRAME,
CHAIN,
GAS_SPENT
FROM month_metrics