{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH seg AS (
    SELECT 
    CHAIN,
    COALESCE(l.NAME, u.CALLED_CONTRACT) AS PROJECT,
    COUNT(DISTINCT u.SENDER) AS NUM_UNIQUE_SENDERS,
    COUNT(u.OP_HASH) AS NUM_OPS,
    ROW_NUMBER() OVER (PARTITION BY CHAIN ORDER BY NUM_UNIQUE_SENDERS DESC) as rank
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS u
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.ERC4337_LABELS_APPS l ON u.CALLED_CONTRACT = l.ADDRESS
    GROUP BY 1,2
)

, agg AS (
    SELECT 
    COALESCE(l.NAME, u.CALLED_CONTRACT) AS PROJECT,
    COUNT(DISTINCT u.SENDER) AS NUM_UNIQUE_SENDERS,
    COUNT(u.OP_HASH) AS NUM_OPS,
    ROW_NUMBER() OVER (ORDER BY NUM_UNIQUE_SENDERS DESC) as rank
    FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS u
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.ERC4337_LABELS_APPS l ON u.CALLED_CONTRACT = l.ADDRESS
    GROUP BY 1
)

SELECT 
'all' AS CHAIN,
PROJECT,
NUM_UNIQUE_SENDERS,
NUM_OPS
FROM agg
WHERE rank <= 10

union all

SELECT 
CHAIN,
PROJECT,
NUM_UNIQUE_SENDERS,
NUM_OPS
FROM seg
WHERE rank <= 10