{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH txns AS (
SELECT 
BUNDLER_NAME,
CHAIN,
COUNT(*) AS NUM_TXNS,
SUM(BUNDLER_REVENUE_USD) AS REVENUE
FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_ENTRYPOINT_TRANSACTIONS
WHERE BUNDLER_REVENUE_USD != 'NaN'
AND BUNDLER_REVENUE_USD < 1000000000
GROUP BY 1,2
),

usops AS (
SELECT 
BUNDLER_NAME,
CHAIN,
COUNT(*) AS NUM_USEROPS
FROM BUNDLEBEAR.DBT_KOFI.ERC4337_ALL_USEROPS
GROUP BY 1,2
)

SELECT 
t.BUNDLER_NAME,
t.CHAIN,
NUM_USEROPS,
NUM_TXNS,
REVENUE
FROM txns t
INNER JOIN usops u 
ON u.BUNDLER_NAME = t.BUNDLER_NAME
AND u.CHAIN = t.CHAIN

UNION ALL 
SELECT 
t.BUNDLER_NAME,
'all' AS CHAIN,
SUM(NUM_USEROPS) AS NUM_USEROPS,
SUM(NUM_TXNS) AS NUM_TXNS,
SUM(REVENUE) AS REVENUE
FROM txns t
INNER JOIN usops u 
ON u.BUNDLER_NAME = t.BUNDLER_NAME
AND u.CHAIN = t.CHAIN
group by 1,2