{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

SELECT 
COUNT(DISTINCT CASE 
  WHEN rn = 1 AND AUTHORIZED_CONTRACT != '0x0000000000000000000000000000000000000000' 
  THEN AUTHORITY 
END) AS LIVE_SMART_WALLETS,
COUNT(*) AS NUM_AUTHORIZATIONS,
COUNT(DISTINCT AUTHORIZED_CONTRACT) AS NUM_AUTHORIZED_CONTRACTS,
COUNT(DISTINCT TX_HASH) AS NUM_SET_CODE_TXNS
FROM (
SELECT 
  AUTHORITY,
  AUTHORIZED_CONTRACT,
  TX_HASH,
  ROW_NUMBER() OVER (PARTITION BY AUTHORITY ORDER BY NONCE DESC, BLOCK_TIME DESC) as rn
FROM 
  {{ ref('erc7702_all_authorizations') }}
)