{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH day_metrics AS (
    SELECT
    TO_VARCHAR(BLOCK_DATE, 'YYYY-MM-DD') as DATE,
    CHAIN,
    'day' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '6 months'
    AND BLOCK_DATE < CURRENT_DATE()
    GROUP BY 1,2,3,4

    UNION ALL
    SELECT
    TO_VARCHAR(BLOCK_DATE, 'YYYY-MM-DD') as DATE,
    'all' AS CHAIN,
    'day' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '6 months'
    AND BLOCK_DATE < CURRENT_DATE()
    GROUP BY 1,2,3,4
)

, week_metrics AS (
    SELECT
    TO_VARCHAR(date_trunc('week', BLOCK_DATE), 'YYYY-MM-DD') as DATE,
    CHAIN,
    'week' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('week', CURRENT_DATE()) - INTERVAL '24 weeks'
    AND BLOCK_DATE < DATE_TRUNC('week', CURRENT_DATE())
    GROUP BY 1,2,3,4

    UNION ALL
    SELECT
    TO_VARCHAR(date_trunc('week', BLOCK_DATE), 'YYYY-MM-DD') as DATE,
    'all' AS CHAIN,
    'week' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('week', CURRENT_DATE()) - INTERVAL '24 weeks'
    AND BLOCK_DATE < DATE_TRUNC('week', CURRENT_DATE())
    GROUP BY 1,2,3,4
)

, month_metrics AS (
    SELECT
    TO_VARCHAR(date_trunc('month', BLOCK_DATE), 'YYYY-MM-DD') as DATE,
    CHAIN,
    'month' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '6 months'
    AND BLOCK_DATE < DATE_TRUNC('month', CURRENT_DATE())
    GROUP BY 1,2,3,4

    UNION ALL
    SELECT
    TO_VARCHAR(date_trunc('month', BLOCK_DATE), 'YYYY-MM-DD') as DATE,
    'all' AS CHAIN,
    'month' AS TIMEFRAME,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    COUNT(DISTINCT OP_HASH) AS NUM_USEROPS
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_ACTIONS a
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
        ON a.AUTHORIZED_CONTRACT = l.ADDRESS
    WHERE TYPE = 'erc-4337 userop'
    AND BLOCK_DATE >= DATE_TRUNC('month', CURRENT_DATE()) - INTERVAL '6 months'
    AND BLOCK_DATE < DATE_TRUNC('month', CURRENT_DATE())
    GROUP BY 1,2,3,4
)

SELECT
DATE,
TIMEFRAME,
CHAIN,
AUTHORIZED_CONTRACT,
NUM_USEROPS
FROM day_metrics

UNION ALL
SELECT
DATE,
TIMEFRAME,
CHAIN,
AUTHORIZED_CONTRACT,
NUM_USEROPS
FROM week_metrics

UNION ALL
SELECT
DATE,
TIMEFRAME,
CHAIN,
AUTHORIZED_CONTRACT,
NUM_USEROPS
FROM month_metrics