{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH latest_date AS (
    SELECT MAX(DAY) AS max_day
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_METRICS_DAILY_AUTH_CONTRACT_USAGE
)

SELECT 
CHAIN2 AS CHAIN,
AUTHORIZED_CONTRACT,
NUM_WALLETS
FROM (
SELECT
CASE WHEN CHAIN = 'cross-chain' THEN 'all'
        ELSE CHAIN
END AS CHAIN2,
COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
SUM(NUM_WALLETS) AS NUM_WALLETS,
ROW_NUMBER() OVER (PARTITION BY CHAIN2 ORDER BY SUM(NUM_WALLETS) DESC) AS rn
FROM BUNDLEBEAR.DBT_KOFI.EIP7702_METRICS_DAILY_AUTH_CONTRACT_USAGE u
LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
ON u.AUTHORIZED_CONTRACT =l.ADDRESS
INNER JOIN latest_date ld 
ON u.DAY = ld.max_day
GROUP BY 1,2
)
WHERE rn <= 15
