{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH ranked_contracts AS (
    SELECT
    DAY,
    CHAIN,
    COALESCE(l.NAME, AUTHORIZED_CONTRACT) AS AUTHORIZED_CONTRACT,
    SUM(NUM_WALLETS) AS NUM_WALLETS,
    ROW_NUMBER() OVER (PARTITION BY DAY, CHAIN ORDER BY SUM(NUM_WALLETS) DESC) AS rank
    FROM BUNDLEBEAR.DBT_KOFI.EIP7702_METRICS_DAILY_AUTH_CONTRACT_USAGE u
    LEFT JOIN BUNDLEBEAR.DBT_KOFI.EIP7702_LABELS_AUTHORIZED_CONTRACTS l
    ON u.AUTHORIZED_CONTRACT =l.ADDRESS
    GROUP BY 1,2,3
)

SELECT
    TO_VARCHAR(DAY, 'YYYY-MM-DD') AS DATE,
    CASE WHEN CHAIN = 'cross-chain' THEN 'all'
    ELSE CHAIN
    END AS CHAIN,
    CASE 
    WHEN rank <= 10 THEN AUTHORIZED_CONTRACT
    ELSE 'other'
    END AS AUTHORIZED_CONTRACT,
    SUM(NUM_WALLETS) AS NUM_WALLETS
FROM ranked_contracts
GROUP BY 1,2,3