{{ config
(
    materialized = 'table',
    copy_grants=true
)
}}

WITH actions AS (
SELECT 
COUNT(*) AS NUM_AUTHORIZATIONS,
COUNT(DISTINCT AUTHORIZED_CONTRACT) AS NUM_AUTHORIZED_CONTRACTS,
COUNT(DISTINCT TX_HASH) AS NUM_SET_CODE_TXNS
FROM (
SELECT 
  AUTHORITY,
  AUTHORIZED_CONTRACT,
  TX_HASH,
  ROW_NUMBER() OVER (PARTITION BY AUTHORITY ORDER BY NONCE DESC, BLOCK_TIME DESC) as rn
FROM 
  {{ ref('eip7702_all_authorizations') }}
)
)

, state AS (
SELECT LIVE_SMART_WALLETS
FROM {{ ref('eip7702_metrics_daily_authority_state') }}
WHERE DAY = CURRENT_DATE()
AND CHAIN = 'cross-chain'
)

SELECT 
LIVE_SMART_WALLETS,
NUM_AUTHORIZATIONS,
NUM_AUTHORIZED_CONTRACTS,
NUM_SET_CODE_TXNS
FROM actions, state