{{ config
(
    materialized = 'table'
)
}}

SELECT TRANSACTION_HASH, BLOCK_TIMESTAMP, TO_ADDRESS, FROM_ADDRESS
FROM (
    SELECT 
        TRANSACTION_HASH, 
        BLOCK_TIMESTAMP, 
        TO_ADDRESS, 
        FROM_ADDRESS,
        ROW_NUMBER() OVER (PARTITION BY TO_ADDRESS ORDER BY BLOCK_TIMESTAMP) AS rn
    FROM CROSSCHAIN.STABLECOIN.TRANSFERS
    WHERE IS_BRIDGE = FALSE
    AND CHAIN = 'tron'
) t
WHERE rn = 1